name: mobile
description: "Warehouse Management System — Platform operasional gudang: inbound, put-away, picking, packing, shipping, dan utilisasi ruang gudang."
publish_to: "none"
version: 1.0.0+1

workspace:
  - packages/core_ui
  - packages/core_services
  - packages/zone
  - packages/product

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dio: ^5.0.0
  flutter_launcher_icons: ^0.13.1

  core_ui:
    path: packages/core_ui
  core_services:
    path: packages/core_services
  zone:
    path: packages/zone
  flutter_dotenv: ^6.0.1
  percent_indicator: ^4.2.5
  mobile_scanner: ^7.2.0
  flutter_slidable: ^4.0.3
  melos: ^7.5.1
  flutter_bloc: ^8.1.2
  get_it: ^9.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - .env

melos:
  scripts:
    analyze:
      description: "Run Flutter analyzer across all workspace packages"
      run: dart run melos exec -- "flutter analyze"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/app_icon.png"
